language: android
android:
  components:
    - tools
    - platform-tools
    # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
    - tools
    - build-tools-26.0.2
    - android-26

    # Ensure some components are always there
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator images
    - sys-img-armeabi-v7a-android-26