language: android
android:
  components:
    - build-tools-$BUILD_TOOLS
    - android-$ANDROID_VERSION
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
env:
  matrix:
    - BUILD_TOOLS=26.0.3  ANDROID_VERSION=26